version: '3'
services:
  api:
    build: backend
    ports:
      - "9808:9808"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.gourl.localhost`)"
      - "traefik.http.services.api-service.loadbalancer.server.port=9808"
    depends_on:
      - redis
    networks:
      - traefik_proxy # Connect this service to your custom network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - traefik_proxy # Connect this service to your custom network

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`gourl.localhost`)"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=3000"
    networks:
      - traefik_proxy # Connect this service to your custom network

networks:
  traefik_proxy:
    external: true
